### PR TITLE
Option to purge jira

### PR DESCRIPTION
**Pull request by vipetrul**
This is for #8 

I had to refactor entire pipeline to allow for better composition and testing.
Added tests for key processes.

Notes about tests:
Replaced MS Tests with NUnit v3 - which allows to write test cases much easier.
Added dependency for FluentAssertions - which allows much easier to compare complex objects (among many other features it supports)

Notes about sync process:
It appears that when toggl time is very small and it is rounded to zero, then JIRA Service will not be able to save it - this is something we need to be aware of.

### CODE REVIEW

**Comment by christianrondeau** [comment]
Hi! I see you've been hard at work :) Usually, big refactorings like this are frowned upon, but it looks like things I would have done and technology I usually prefer, so I'm good with it :)

You'll want however to watch for tabs v.s. spaces (this project use tabs) - if you use Visual Studio 2017, you can create a .editorconfig file so that you don't have to change your environment (e.g. https://github.com/jawa-the-hutt/lz-string-csharp/blob/master/.editorconfig though this one uses tabs)

I'll code review this as soon as I can (let me know if you plan on doing further structural changes), but this looks pretty good at a glance! I appreciate the new tests, this will make my job easier.

**Comment by vipetrul** [comment]
> You'll want however to watch for tabs v.s. spaces (this project use tabs) - if you use Visual Studio 2017, you can create a .editorconfig file so that you don't have to change your environment (e.g. https://github.com/jawa-the-hutt/lz-string-csharp/blob/master/.editorconfig though this one uses tabs)

Thank you - I saw this when I was comparing new vs old files. Now I know how to control this per project.

>let me know if you plan on doing further structural changes

I have nothing new planned - just need to determine what causing CI to throw `System.BadImageFormatException: Could not load file or assembly 'Toggl, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorr` . Probably something to do with 32 vs 64 bit architecture...

**Comment by vipetrul** [comment]
I believe there is a problem with current PR:
Since toggl (source) returns only entries for specific user, and jira returns entries for all users - purge will delete all entries that were created by others users.

I need to think about this  ...

**Comment by vipetrul** [comment]
so we need to make a determination:
* user either only allow to sync their own entries
* or user can sync all records for a given jira project (although it will appear that only that one user created all these entries). also not sure if it is possible to create time entries on other user behalf.

What do you think?

**Comment by christianrondeau** [comment]
I would definitely go with only syncing your own entries. Since Toggl's worklogs are user-specific anyway, it would not make sense to modify other users entries in JIRA.

**Comment by vipetrul** [comment]
Sounds good, i was thinking along the same lines.

**Comment by vipetrul** [comment]
Today I showed this tool to my coworkers that had to sync toggl time entries from one of the projects. It worked pretty well!
One suggestion that came out of it - (y/n) questions should not automatically execute when key is pressed. What was happening, is that they were pressing `y` then `Enter` which executed two commands `y` then `n` (i.e. key != 'y').

What are your thoughts on this?

**Comment by vipetrul** [comment]
Bugs found:
* Toggl time entry had a key ABC-123, and was sync'ed with JIRA's issue ANC-123 . Later description was modified to ABC-456, but sync process only updated the description of work log entry, but never re-assigned this work log entry to corresponding jira issue.
* When orphaned work log entries were deleted from JIRA, remaining time stayed unchanged. When new entries were added to JIRA, remaining time increased based on entered new value.

I will be working on them.

**Comment by christianrondeau** [comment]
The whole y/n flow feels weird. I'm a Vim user, so pressing Enter after a command seems to much :) Here's what I'd like (this would probably be another issue though)

* Show all entries at once
* `y` enables it and moves to the next
* `n` disables it and moves to the next
* `j` and `k` move down and up in the list
* `Y` accepts all
* `N` refuses all
* `q` quits
* `Enter` sends entries (probably with a confirmation)

That would be something using e.g. ncurses (https://github.com/sushihangover/CursesSharp).

But that's way out of this issue :) My point being that "y" and "enter" makes twice the keypresses...

The "negative" impact of pressing "y" is pretty minimal, so as long as it's clear, I think it's okay.

As for the first bug, I'd be curious how you'll "fix" this... if it was synced with another JIRA number, I guess it's normal it's not finding it. Unless you can get a "description history" for the Toggl entry, I think that's fine.

For the second bug, you're right, it should either stay unchanged for both, or update for both (I prefer the former).

**Comment by vipetrul** [comment]
I believe first bug was resolved by my previous commit, corresponding test scenario was added as well.
Tomorrow I will be looking into JIRA API  documentation in order to solve 2nd problem.

> Please open a separate issue to discuss this, and keep the PR lean :)

Will do 👍

**Comment by vipetrul** [comment]
> When orphaned work log entries were deleted from JIRA, remaining time stayed unchanged. When new entries were added to JIRA, remaining time increased based on entered new value.

My initial assessment was wrong. It appears user who manually edited work logs in jira made wrong adjustments in time remaining.

Please proceed with review, I'm not planning to modifying anything else at this moment.

**Comment by christianrondeau** [comment]
Thanks. Might not be immediate, I have some major projects going on, but I'll do my best :)

**Comment by dstj** [comment]
I'll be testing this pull request this week as I enter my work log. Will let you know my findings.

**Comment by dstj** [comment]
Hi,

To be able to compile, I had to update to `RestSharp, Version=105.2.3.0` (form `104.1`) in the `JiraRestClient` submodules.

My first test (sync 2 days of work logs) was very slow. The first two lines of `WorksheetSyncService.Synchronize()` took around 2+ minutes to complete.

```
public SyncReport Syncronize(DateTime fromDate, DateTime toDate, IEnumerable<string> jiraProjectKeys, bool doPurge, int roundMinutes)
{
	var sourceEntries = _source.GetEntries(fromDate, toDate, jiraProjectKeys);
	var targetEntries = _target.GetEntries(fromDate, toDate, jiraProjectKeys);
```

**Comment by vipetrul** [comment]
I suspect that `var targetEntries = _target.GetEntries(fromDate, toDate, jiraProjectKeys);` took the longest to complete, because it recursively retrieves workLog entries for each updated JIRA item. Although in our environment this operation just takes ~5 seconds, I can see how it can be much slower on other environments.
How many projects are you trying to sync? and approx how many time entries?

Note. I just pushed a small change to JiraRestService class, make sure you pull it when you test.

If we cannot find a better way to retrieve workLog entries from target source, then we can consider performing these operations async to boost performance.

**Comment by vipetrul** [comment]
@dstj , you right - if there are many projects to sync, getting all workLog entries from source (JIRA) will take a while. I did update current implementation of `JiraRepository.GetEntries` to run asynchronously, which cuts the execution time approx in half. 

To expedite the process even further, we need to use a more efficient way to retrieve work log entries form JIRA. JIRA API does have an endpoint to [Get ids of worklogs modified since
](https://docs.atlassian.com/jira/REST/cloud/#api/2/worklog ), but our current JIRA service doesn't have it implemented.

**Comment by christianrondeau** [comment]
I guess we can just make the JSON calls directly then. The library was a shortcut, but if it's creating more trouble than necessary...

This being said, apart from being slow, if it works and it can be turned off without negative impact on performance, I'll accept the PR anyway, since it works for "smaller projects" :) @dstj did you try disabling purge? If it works for you, I'll just accept it: https://github.com/christianrondeau/jira-toggl-sync/pull/10/commits/f0bc59bbebf7a6a37b237c32d17159aad7f23755#diff-cb919c6f2f938d79bd41d95c5e57ea13R56

If you feel like making another PR for the speed, feel free :) I have no emotional attachment to the toggl and the jira librairies I use today ;)

**Comment by vipetrul** [comment]
@christianrondeau , you are missing couple latest commits.
Agree that performance can be addressed in separate PR. If purge is disabled, then performance should be same as before, since no records from source are being retrieved.

**Comment by christianrondeau** [comment]
Sounds good to me. Let's close this then, we can always improve later. Thank you @vipetrul for your contribution, and I'm glad to know the tool is useful to you :)

**Pull request merged**
